import Anteater from ('./models/Anteater.js')
import Brownbear from ('./models/Brownbear.js')
import Cobra from ('./models/Cobra.js')
import Duck from ('./models/Duck.js')
import Elephant from ('./models/Elephant.js')
import Falcon from ('./models/Falcon.js')
import GilaMonster from ('./models/Gilamonster.js')
import Hedgehog from ('./models/Hedgehog.js')
import Iguana from ('./models/Iguana.js')
import Kangaroo from ('./models/Kangaroo.js')
import Leopard from ('./models/Leopard')
import Malayantiger from ('./models/Malayantiger.js')
import Newt from ('./models/newt.js')
import Ostrich from ('./models/Ostrich.js')
import Panda from ('./models/Panda.js')
import Queensnake from ('./models/Queensnake.js')
import Rattlesnake from ('./models/Rattlesnake.js')
import Sloth from ('./models/Sloth.js')
import Tasdevil from ('./models/TasDevil.js')
import Uakari from ('./models/Uakari.js')
import Vampirebat from ('./models/Uakari.js')
import Worthog from ('./models/Worthog.js')

let Fred = new Anteater("Fred", "White", 75, "long", "mammal")
let Buddy = new Brownbear("Buddy", "Brown", 1000, "Pointy", "mammal")
let Isssak = new Cobra("Isssak", "Black", 96, true, "reptile")
let Donald = new Duck("Donald", "Black", 48, 10, "bird")
let Dumbo = new Elephant("Dumbo", 20, 6, 13000, 25, "mammal")
let Thunger = new Falcon("Thunder", "Blue", 38, "birds", 'bird')
let Archimedes = new GilaMonster("Archimedes", 22, "eggs", true, "reptile")
let Hodges = new Hedgehog("Hodges", 22, 7, "mammal")
let Spike = new Iguana("Spike", 56, 'green', 'leaves', false, 'reptile')
let MJ = new Kangaroo("MJ", 120, 'flowers', 'female', 'marsupial')
let KingLeo = new Leopard("King Leo", 60, male, 'meat', 36, 'cat')
let Rajah = new Malayantiger("Rajah", 400, male, 'meat', 40, 'cat')
let Slinky = new Newt("Slinky", 6, 'bugs', 'amphibian')
let Ozzy = new Ostrich("Ozzy", 96, 43, 6, 'bird')
let Noodles = new Panda("Noodles", 180, 20, 'female', 'mammal')
let Regina = new Queensnake('Regina', 30, 'crayfish', 'male', false, 'reptile')
let Cowboy = new Rattlesnake('Cowboy', 68, 'male', 'mice', true, 'reptile')
let Bolt = new Sloth('Bolt', 30, 80, female, 2, 'mammal')
let Molly = new Tasdevil("Molly", 30, 25, 'female', 'crazy', 'marsupial')
let Boots = new Uakari("Boots", 20, 7, female, 'fruit', 'monkey')
let Dracula = new Vampirebat("Dracula", 1, 10, 'male', 'bird')
let Pumba = new Worthog("Pumba", 200, 30, female, "pig")
